AZURE_OPENAI_KEY = "mUioPGaWXpVytXwabznwffKEXYyRFYTijQcRim2zgGAfoVSkZO23JQQJ99CBACHYHv6XJ3w3AAAAACOGmOy9"
AZURE_OPENAI_ENDPOINT = "https://abhis-mlv09ybo-eastus2.cognitiveservices.azure.com/"
AZURE_OPENAI_DEPLOYMENT = "gpt-4o"